// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyCopyrightAttribute("Copyright(c) 2016 forloop - Russ Cam http://forloop.co.uk")]
[assembly: AssemblyDescriptionAttribute("AsciiDoc processor for .NET")]
[assembly: AssemblyCompanyAttribute("forloop")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: InternalsVisibleTo("AsciiDocNet.Tests")]
