// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("AsciiDocNet.Tests")]
[assembly: AssemblyCopyrightAttribute("Copyright(c) 2016 forloop - Russ Cam http://forloop.co.uk")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("forloop")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0-alpha5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "AsciiDocNet.Tests";
        internal const System.String AssemblyCopyright = "Copyright(c) 2016 forloop - Russ Cam http://forloop.co.uk";
        internal const System.String AssemblyDescription = "";
        internal const System.String AssemblyCompany = "forloop";
        internal const System.String AssemblyConfiguration = "Release";
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0";
        internal const System.String AssemblyInformationalVersion = "1.0.0-alpha5";
    }
}
