// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright(c) 2016 forloop - Russ Cam http://forloop.co.uk")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("forloop")]
[assembly: AssemblyConfigurationAttribute("Release")]
