// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AsciiDocNet.Tests.Specifications
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CrossReferencesFeature : Xunit.IClassFixture<CrossReferencesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CrossReferences.feature"
#line hidden
        
        public CrossReferencesFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Cross References", "  In order to create links to other sections\r\n  As a writer\r\n  I want to be able " +
                    "to use a cross reference macro", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(CrossReferencesFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Create a cross reference from an AsciiDoc cell to a section", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Cross References")]
        [Xunit.TraitAttribute("Description", "Create a cross reference from an AsciiDoc cell to a section")]
        public virtual void CreateACrossReferenceFromAnAsciiDocCellToASection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a cross reference from an AsciiDoc cell to a section", new string[] {
                        "ignore"});
#line 9
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 10
  testRunner.Given("the AsciiDoc source", "|===\r\na|See <<_install>>\r\n|===\r\n\r\n== Install\r\n\r\nInstructions go here.", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
  testRunner.Then("the result should match the HTML source", @"table.tableblock.frame-all.grid-all.spread
  colgroup
    col style='width: 100%;'
  tbody
    tr
      td.tableblock.halign-left.valign-top
        div
          .paragraph: p
            'See
            a href='#_install' Install
.sect1
  h2#_install Install
  .sectionbody
    .paragraph: p Instructions go here.", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Create a cross reference using the target section title", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Cross References")]
        [Xunit.TraitAttribute("Description", "Create a cross reference using the target section title")]
        public virtual void CreateACrossReferenceUsingTheTargetSectionTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a cross reference using the target section title", new string[] {
                        "ignore"});
#line 42
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 43
  testRunner.Given("the AsciiDoc source", "== Section One\r\n\r\ncontent\r\n\r\n== Section Two\r\n\r\nrefer to <<Section One>>", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 54
  testRunner.Then("the result should match the HTML source", ".sect1\r\n  h2#_section_one Section One\r\n  .sectionbody: .paragraph: p content\r\n.se" +
                    "ct1\r\n  h2#_section_two Section Two\r\n  .sectionbody: .paragraph: p\r\n    \'refer to" +
                    "\r\n    a href=\'#_section_one\' Section One", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Create a cross reference using the target reftext", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Cross References")]
        [Xunit.TraitAttribute("Description", "Create a cross reference using the target reftext")]
        public virtual void CreateACrossReferenceUsingTheTargetReftext()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a cross reference using the target reftext", new string[] {
                        "ignore"});
#line 69
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 70
  testRunner.Given("the AsciiDoc source", "[reftext=\"the first section\"]\r\n== Section One\r\n\r\ncontent\r\n\r\n== Section Two\r\n\r\nref" +
                    "er to <<the first section>>", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 81
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 82
  testRunner.Then("the result should match the HTML source", ".sect1\r\n  h2#_section_one Section One\r\n  .sectionbody: .paragraph: p content\r\n.se" +
                    "ct1\r\n  h2#_section_two Section Two\r\n  .sectionbody: .paragraph: p\r\n    \'refer to" +
                    "\r\n    a href=\'#_section_one\' the first section", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Create a cross reference using the formatted target title", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Cross References")]
        [Xunit.TraitAttribute("Description", "Create a cross reference using the formatted target title")]
        public virtual void CreateACrossReferenceUsingTheFormattedTargetTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a cross reference using the formatted target title", new string[] {
                        "ignore"});
#line 96
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 97
  testRunner.Given("the AsciiDoc source", "== Section *One*\r\n\r\ncontent\r\n\r\n== Section Two\r\n\r\nrefer to <<Section *One*>>", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 108
  testRunner.Then("the result should match the HTML source", @"<div class=""sect1"">
  <h2 id=""_section_strong_one_strong"">
    Section <strong>One</strong>
</h2>
<div class=""sectionbody"">
<div class=""paragraph"">
<p>content</p>
</div>
</div>
</div>
   <div class=""sect1"">
     <h2 id=""_section_two"">Section Two</h2>
<div class=""sectionbody"">
<div class=""paragraph"">
<p>refer to
       <a href=""#_section_strong_one_strong"">
         Section <strong>One</strong>
 </a>
</p>
  </div>
</div>
</div>", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CrossReferencesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CrossReferencesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
