// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AsciiDocNet.Tests.Specifications
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PassBlocksFeature : Xunit.IClassFixture<PassBlocksFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PassBlocks.feature"
#line hidden
        
        public PassBlocksFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Pass Blocks", "  In order to pass content through unprocessed\r\n  As a writer\r\n  I want to be abl" +
                    "e to mark passthrough content using a pass block", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(PassBlocksFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Render a pass block without performing substitutions by default to HTML")]
        [Xunit.TraitAttribute("FeatureTitle", "Pass Blocks")]
        [Xunit.TraitAttribute("Description", "Render a pass block without performing substitutions by default to HTML")]
        public virtual void RenderAPassBlockWithoutPerformingSubstitutionsByDefaultToHTML()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Render a pass block without performing substitutions by default to HTML", ((string[])(null)));
#line 8
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 9
  testRunner.Given("the AsciiDoc source", ":name: value\r\n\r\n++++\r\n<p>{name}</p>\r\n\r\nimage:tiger.png[]\r\n++++", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
  testRunner.Then("the result should match the HTML source", "<p>{name}</p>\r\n\r\nimage:tiger.png[]", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Render a pass block performing explicit substitutions to HTML", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Pass Blocks")]
        [Xunit.TraitAttribute("Description", "Render a pass block performing explicit substitutions to HTML")]
        public virtual void RenderAPassBlockPerformingExplicitSubstitutionsToHTML()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Render a pass block performing explicit substitutions to HTML", new string[] {
                        "ignore"});
#line 49
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 50
  testRunner.Given("the AsciiDoc source", ":name: value\r\n\r\n[subs=\"attributes,macros\"]\r\n++++\r\n<p>{name}</p>\r\n\r\nimage:tiger.pn" +
                    "g[]\r\n++++", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 61
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 62
  testRunner.Then("the result should match the HTML source", "<p>value</p>\r\n\r\n<span class=\"image\"><img src=\"tiger.png\" alt=\"tiger\"></span>", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PassBlocksFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PassBlocksFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
