// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AsciiDocNet.Tests.Specifications
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TextFormattingFeature : Xunit.IClassFixture<TextFormattingFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TextFormatting.feature"
#line hidden
        
        public TextFormattingFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Text Formatting", "  In order to apply formatting to the text\r\n  As a writer\r\n  I want to be able to" +
                    " markup inline text with formatting characters", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(TextFormattingFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Convert text that contains superscript and subscript characters")]
        [Xunit.TraitAttribute("FeatureTitle", "Text Formatting")]
        [Xunit.TraitAttribute("Description", "Convert text that contains superscript and subscript characters")]
        public virtual void ConvertTextThatContainsSuperscriptAndSubscriptCharacters()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Convert text that contains superscript and subscript characters", ((string[])(null)));
#line 7
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 8
  testRunner.Given("the AsciiDoc source", "_v_~rocket~ is the value\r\n^3^He is the isotope\r\nlog~4~x^n^ is the expression\r\nM^m" +
                    "e^ White is the address\r\nthe 10^th^ point has coordinate (x~10~, y~10~)", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
  testRunner.Then("the result should match the HTML source", @"<div class=""paragraph"">
<p><em>v</em><sub>rocket</sub> is the value
<sup>3</sup>He is the isotope
log<sub>4</sub>x<sup>n</sup> is the expression
M<sup>me</sup> White is the address
the 10<sup>th</sup> point has coordinate (x<sub>10</sub>, y<sub>10</sub>)</p>
</div>", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Convert text that has ex-inline literal formatting")]
        [Xunit.TraitAttribute("FeatureTitle", "Text Formatting")]
        [Xunit.TraitAttribute("Description", "Convert text that has ex-inline literal formatting")]
        public virtual void ConvertTextThatHasEx_InlineLiteralFormatting()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Convert text that has ex-inline literal formatting", ((string[])(null)));
#line 29
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 30
  testRunner.Given("the AsciiDoc source", "Use [x-]`{asciidoctor-version}` to print the version of Asciidoctor.", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
  testRunner.Then("the result should match the HTML source", "<div class=\"paragraph\">\r\n<p>Use <code>{asciidoctor-version}</code> to print the v" +
                    "ersion of Asciidoctor.</p>\r\n</div>", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Convert text that has ex-inline monospaced formatting", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Text Formatting")]
        [Xunit.TraitAttribute("Description", "Convert text that has ex-inline monospaced formatting")]
        public virtual void ConvertTextThatHasEx_InlineMonospacedFormatting()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Convert text that has ex-inline monospaced formatting", new string[] {
                        "ignore"});
#line 44
  this.ScenarioSetup(scenarioInfo);
#line hidden
#line 45
  testRunner.Given("the AsciiDoc source", ":encoding: UTF-8\r\n\r\nThe document is assumed to be encoded as [x-]+{encoding}+.", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
  testRunner.When("it is converted to html", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
  testRunner.Then("the result should match the HTML source", "<div class=\"paragraph\">\r\n<p>The document is assumed to be encoded as <code>UTF-8<" +
                    "/code>.</p>\r\n</div>", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TextFormattingFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TextFormattingFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
